


# Creating Array in python

In [1]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

# Create Matrix and check its shape and length

In [2]:
## create matrix with nested matrix
b = np.array([[1,2],[3,4],[5,6],[6,7]])
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [6, 7]])

In [3]:
# To find length lets use following command
len(b)

4

In [4]:
#Let's check shape of matrix
b.shape
##a.shape

(4, 2)

# Create a matrix A and transpose it

In [5]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A


array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
transpose_A = A.T
transpose_A


array([[1, 3, 5],
       [2, 4, 6]])

# ADD two matrices

In [7]:
B = np.array([[2,3],[7,8],[8,9]])
B


array([[2, 3],
       [7, 8],
       [8, 9]])

In [8]:
# Add matrices A and B
C = A + B
C

array([[ 3,  5],
       [10, 12],
       [13, 15]])

# ADD scalar to matrices

In [9]:
D = 4 + A
D

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
# matrix-vector multiplication
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define vector
B = array([0.5, 0.5])
print(B)
# multiply
C = A.dot(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]
[1.5 3.5 5.5]


In [15]:
# matrix-scalar multiplication
from numpy import array
# define matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# define scalar
b = 0.5
print(b)
# multiply
C = A * b
print(C)

[[1 2]
 [3 4]
 [5 6]]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


In [13]:
# matrix division
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# divide matrices
C = A / B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


# Broadcasting
Numpy can handle operations on arrays of different shapes. The smaller array will be extended to match the shape of the bigger one. The advantage is that this is done in C under the hood (like any vectorized operations in Numpy).The scalar F was converted in an array of same shape as E.

Here is another generic example:


In [10]:
E = np.array([[1, 2], [3, 4], [5, 6]])
E

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
F = np.array([[2], [4], [6]])
F

array([[2],
       [4],
       [6]])

In [12]:
G = E + F
G

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

# Limitations of Broadcasting
Broadcasting is a handy shortcut that proves very useful in practice when working with NumPy
arrays. That being said, it does not work for all cases, and in fact imposes a strict rule that
must be satised for broadcasting to be performed. Arithmetic, including broadcasting, can
only be performed when the shape of each dimension in the arrays are equal or one has the
dimension size of 1. The dimensions are considered in reverse order, starting with the trailing
dimension; for example, looking at columns before rows in a two-dimensional case.
This make more sense when we consider that NumPy will in eect pad missing dimensions
with a size of 1 when comparing arrays. Therefore, the comparison between a two-dimensional
array A with 2 rows and 3 columns and a vector b with 3 elements:

In [1]:
# broadcasting error
from numpy import array
# define two-dimensional array
o = array([
[1, 2, 3],
[1, 2, 3]])
print(o.shape)
# define one-dimensional array
p = array([1, 2])
print(p.shape)
# attempt broadcast
q = o + p
print(q)
##Running the example first prints the shapes of the arrays then raises an error when attempting to broadcast, as we expected.

(2, 3)
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

# Dot product with Numpy
The Numpy function dot() can be used to compute the matrix product (or dot product). Let’s try to reproduce the last exemple:

In [13]:
H = np.array([[1, 2], [3, 4], [5, 6]])
H

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
I = np.array([[2], [4]])
I

array([[2],
       [4]])

In [15]:
J = np.dot(H, I) ## A.dot(B)
J

array([[10],
       [22],
       [34]])

# Properties of the dot product
We will now see some interesting properties of the matrix multiplication. It will become useful as we move forward in the chapters. Using simple examples for each property will provide a way to check them while we get used to the Numpy functions.

Matrices mutliplication is distributive
A(B+C)=AB+AC


Matrices mutliplication is associative
A(BC)=(AB)C


Matrices mutliplication is not commutative 
AB≠BA




In [16]:
# create zero array
from numpy import zeros
I = zeros([3,5])
print(I)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
# create one array
from numpy import ones
J = ones([7])
print(J)

[1. 1. 1. 1. 1. 1. 1.]


## Combining Arrays vertically


In [18]:
# create array with vstack
from numpy import array
from numpy import vstack
# create first array
K1 = array([1,2,3])
print(K1)
# create second array
K2 = array([4,5,6])
print(K2)
# vertical stack
K3 = vstack((K1, K2))
print(K3)
print(K3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


# Combining arrays horizontally

In [19]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
l1 = array([1,2,3])
print(l1)
# create second array
l2 = array([4,5,6])
print(l2)
# create horizontal stack
l3 = hstack((l1, l2))
print(l3)
print(l3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


In [20]:
## creating array
m = (1,2,3,4)
n = array(m)
n

array([1, 2, 3, 4])

# Defining a Vector
We can represent a vector in Python as a NumPy array. A NumPy array can be created from
a list of numbers. For example, below we define a vector with the length of 3 and the integer
values 1, 2 and 3.

In [2]:
# Import required library
from numpy import array
# define vector
v = array([1, 2, 3])
print(v)

[1 2 3]


In [3]:
# vector addition
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# add vectors
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


In [4]:
# vector subtraction
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([0.5, 0.5, 0.5])
print(b)
# subtract vectors
c = a - b
print(c)

[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]


In [5]:
# vector multiplication
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


In [6]:
# vector division
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# divide vectors
c = a / b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


In [7]:
# vector dot product
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


In [10]:
# vector-scalar multiplication
from numpy import array
# define vector
a = array([1, 2, 3])
print(a)
# define scalar
s = 0.5
print(s)
# multiplication
c = s * a
print(c)

[1 2 3]
0.5
[0.5 1.  1.5]


In [11]:
# vector L1 norm
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
l1 = norm(a, 1)
print(l1)

[1 2 3]
6.0


In [12]:
# vector L2 norm
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
l2 = norm(a)
print(l2)

[1 2 3]
3.7416573867739413


# Types of Matrices

In [17]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# lower triangular matrix
lower = tril(M)
print(lower)
# upper triangular matrix
upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [18]:
# diagonal matrix
from numpy import array
from numpy import diag
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# extract diagonal vector
d = diag(M)
print(d)
# create diagonal matrix from vector
D = diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
